name: gender_picker
description: A very nice and reactive library for gender picking whether in Horizontal or vertical way
version: 1.1.0
homepage: https://github.com/muhammadmateen027/gender_picker

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  assets:
    - assets/images/
    